
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Oct 16 17:20:29 GMT-03:00 2010
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 19;
  public static final int VAL = 29;
  public static final int MENOR = 8;
  public static final int PUNTO = 2;
  public static final int CORCIERRA = 26;
  public static final int INT = 31;
  public static final int IGUAL = 4;
  public static final int MENORIGUAL = 7;
  public static final int SUMA = 12;
  public static final int ORELSE = 14;
  public static final int NOT = 21;
  public static final int CONCAT = 15;
  public static final int DIVREAL = 17;
  public static final int NIL = 27;
  public static final int ID = 30;
  public static final int CONS = 11;
  public static final int STRING = 33;
  public static final int ANDALSO = 20;
  public static final int COMA = 5;
  public static final int DISTINTO = 6;
  public static final int MAYOR = 10;
  public static final int EOF = 0;
  public static final int DIVINT = 18;
  public static final int MAYORIGUAL = 9;
  public static final int MINUS = 22;
  public static final int error = 1;
  public static final int PTOCOMA = 3;
  public static final int PARCIERRA = 24;
  public static final int PARABRE = 23;
  public static final int REAL = 32;
  public static final int MUL = 16;
  public static final int CORABRE = 25;
  public static final int FUN = 28;
  public static final int RESTA = 13;
}

